import { Poll } from "@/lib/package/entities/poll.entity";

export const POLL_MOCK: Poll[] = [
  {
    id: "1",
    name: "poll 1",
    ballots: [
      { id: "1-1", name: "Huy Le" },
      { id: "1-2", name: "Do Lap" },
      { id: "1-3", name: "Lam Vu" },
      { id: "1-4", name: "Hoang Duong" },
      { id: "1-5", name: "Duc Tran" },
    ],
    voters: [
      "20020202@vnu.edu.vn",
      "20020198@vnu.edu.vn",
      "example@gmail.com",
      "only.fans@gmail.com",
      "voter@gmail.com",
    ],
    status: "ready",
    startTime: new Date(),
    endTime: new Date(),
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Bau cu cho nhom thuyet trinh hay nhat",
    ballots: [
      { id: "1-1", name: "Huy Le" },
      { id: "1-2", name: "Do Lap" },
      { id: "1-3", name: "Lam Vu" },
      { id: "1-4", name: "Hoang Duong" },
      { id: "1-5", name: "Duc Tran" },
    ],
    voters: [
      "20020202@vnu.edu.vn",
      "20020198@vnu.edu.vn",
      "example@gmail.com",
      "only.fans@gmail.com",
      "voter@gmail.com",
    ],
    status: "ready",
    startTime: new Date(),
    endTime: new Date(),
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Test thoi",
    ballots: [
      { id: "1-1", name: "Huy Le" },
      { id: "1-2", name: "Do Lap" },
      { id: "1-3", name: "Lam Vu" },
      { id: "1-4", name: "Hoang Duong" },
      { id: "1-5", name: "Duc Tran" },
    ],
    voters: [
      "20020202@vnu.edu.vn",
      "20020198@vnu.edu.vn",
      "example@gmail.com",
      "only.fans@gmail.com",
      "voter@gmail.com",
    ],
    status: "open",
    startTime: new Date(),
    endTime: new Date(),
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "Dung lam phien",
    ballots: [
      { id: "1-1", name: "Huy Le" },
      { id: "1-2", name: "Do Lap" },
      { id: "1-3", name: "Lam Vu" },
      { id: "1-4", name: "Hoang Duong" },
      { id: "1-5", name: "Duc Tran" },
    ],
    voters: [
      "20020202@vnu.edu.vn",
      "20020198@vnu.edu.vn",
      "example@gmail.com",
      "only.fans@gmail.com",
      "voter@gmail.com",
    ],
    status: "open",
    startTime: new Date(),
    endTime: new Date(),
    createdAt: new Date(),
  },
  {
    id: "5",
    name: "Ai yeu thay Do nhat",
    ballots: [
      { id: "1-1", name: "Huy Le" },
      { id: "1-2", name: "Do Lap" },
      { id: "1-3", name: "Lam Vu" },
      { id: "1-4", name: "Hoang Duong" },
      { id: "1-5", name: "Duc Tran" },
    ],
    voters: [
      "20020202@vnu.edu.vn",
      "20020198@vnu.edu.vn",
      "example@gmail.com",
      "only.fans@gmail.com",
      "voter@gmail.com",
    ],
    status: "closed",
    startTime: new Date(),
    endTime: new Date(),
    createdAt: new Date(),
  },
];
